const copy = (en, hi, hinglish) => ({ en, hi, hinglish });

export const INITIAL_FORM = {
  name: "",
  consent: false,
  age: "",
  gender: "",
  smoking: "",
  cigarettes_per_day: "",
  diabetes: "",
  family_history: "",
  activity_level: "",
  sitting: "",
  exertion_response: "",
  chest_symptom_pattern: "",
  breathlessness_pattern: "",
  recovery_after_effort: "",
  stress: "",
  stress_trigger_pattern: "",
  sleep_quality: "",
  sleep_hours: "",
  snoring_pattern: "",
  diet: "",
  fruit_veg_servings: "",
  sugary_drinks: "",
  salt_intake: "",
  meal_timing_pattern: "",
  systolic_bp: "",
  diastolic_bp: "",
  cholesterol: "",
  hdl_cholesterol: "",
  ldl_cholesterol: "",
  fasting_glucose: "",
  triglycerides: "",
};

export const SPLASH_LINES = [
  copy(
    "We read the quiet signals your routine leaves on your heart.",
    "हम उन सूक्ष्म संकेतों को पढ़ते हैं जो आपकी दिनचर्या आपके हृदय पर छोड़ती है।",
    "Hum un subtle signals ko padhte hain jo aapki routine aapke heart par chhodti hai.",
  ),
  copy(
    "Then we turn them into guidance grounded in real medical standards.",
    "फिर हम उन्हें वास्तविक चिकित्सीय मानकों पर आधारित मार्गदर्शन में बदलते हैं।",
    "Phir hum unhe real medical standards par based guidance mein badalte hain.",
  ),
];

export const LANDING_PROMPTS = [
  copy(
    "A data-driven read of how your daily patterns affect cardiovascular health.",
    "आपकी दैनिक आदतें हृदय-स्वास्थ्य को कैसे प्रभावित करती हैं, इसका डेटा-आधारित विश्लेषण।",
    "Aapki daily habits heart health ko kaise affect karti hain, uska data-driven analysis.",
  ),
  copy(
    "Real thresholds. Real reasoning. Personalized to your data.",
    "वास्तविक क्लिनिकल थ्रेशहोल्ड। स्पष्ट तर्क। आपके डेटा के अनुसार व्यक्तिगत विश्लेषण।",
    "Real clinical thresholds. Clear reasoning. Aapke data ke hisaab se personalized analysis.",
  ),
  copy(
    "From global cardiovascular standards to your specific numbers - clear, practical insight.",
    "वैश्विक हृदय-मानकों से लेकर आपके विशिष्ट मानों तक - स्पष्ट और उपयोगी समझ।",
    "Global cardiovascular standards se lekar aapke specific numbers tak - clear aur practical insight.",
  ),
];

export const LOAD_MESSAGES = [
  copy(
    "Linking symptoms, habits, and early clinical risk signals.",
    "लक्षणों, आदतों और प्रारम्भिक क्लिनिकल जोखिम-संकेतों को जोड़ा जा रहा है।",
    "Symptoms, habits aur early clinical risk signals ko joda ja raha hai.",
  ),
  copy(
    "Applying cardiovascular thresholds and rule-based medical checks.",
    "कार्डियोवैस्कुलर थ्रेशहोल्ड और नियम-आधारित चिकित्सीय जाँच लागू की जा रही हैं।",
    "Cardiovascular thresholds aur rule-based medical checks apply kiye ja rahe hain.",
  ),
  copy(
    "Building a patient-specific risk picture from your answers.",
    "आपके उत्तरों से रोगी-विशिष्ट जोखिम-चित्र तैयार किया जा रहा है।",
    "Aapke answers se patient-specific risk picture banayi ja rahi hai.",
  ),
  copy(
    "Preparing your final analysis and care narrative.",
    "आपका अंतिम विश्लेषण और देखभाल-विवरण तैयार किया जा रहा है।",
    "Aapka final analysis aur care narrative tayyar kiya ja raha hai.",
  ),
];

export const QUESTION_BANK = [
  {
    id: "age",
    kind: "number",
    min: 18,
    max: 100,
    placeholder: "32",
    vibe: "vitals",
    title: copy("What is your age?", "आपकी आयु क्या है?", "Aapki age kya hai?"),
    body: copy(
      "Age changes how cardiovascular symptoms, risk, and recovery are interpreted.",
      "आयु से यह तय होता है कि हृदय-सम्बन्धी लक्षण, जोखिम और रिकवरी को कैसे समझा जाए।",
      "Age se yeh decide hota hai ki heart-related symptoms, risk aur recovery ko kaise samjha jaye.",
    ),
    micro: copy("Age recorded.", "आयु दर्ज हो गई।", "Age record ho gayi."),
    ask: () => true,
  },
  {
    id: "gender",
    kind: "choice",
    vibe: "vitals",
    title: copy("Biological sex", "जैविक लिंग", "Biological sex"),
    body: copy(
      "Sex-specific cardiovascular patterns still matter in risk interpretation.",
      "जोखिम की व्याख्या में जैविक लिंग से जुड़े कार्डियोवैस्कुलर पैटर्न अभी भी महत्त्वपूर्ण हैं।",
      "Risk interpretation mein biological sex ke cardiovascular patterns abhi bhi important hote hain.",
    ),
    micro: copy("Baseline updated.", "बेसलाइन अपडेट हो गई।", "Baseline update ho gayi."),
    options: [
      { value: "male", label: copy("Male", "पुरुष", "Male"), note: copy("Male baseline", "पुरुष बेसलाइन", "Male baseline") },
      { value: "female", label: copy("Female", "महिला", "Female"), note: copy("Female baseline", "महिला बेसलाइन", "Female baseline") },
      { value: "other", label: copy("Other / prefer not to say", "अन्य / बताना नहीं चाहते", "Other / batana nahin chahte"), note: copy("Average baseline", "औसत बेसलाइन", "Average baseline") },
    ],
    ask: () => true,
  },
  {
    id: "smoking",
    kind: "choice",
    vibe: "vitals",
    title: copy("Do you currently smoke?", "क्या आप वर्तमान में धूम्रपान करते हैं?", "Kya aap abhi smoke karte ho?"),
    body: copy(
      "Smoking remains one of the strongest reversible cardiovascular risk drivers.",
      "धूम्रपान अभी भी हृदय-जोखिम बढ़ाने वाले सबसे शक्तिशाली परिवर्तनीय कारणों में से एक है।",
      "Smoking abhi bhi heart-risk badhane wale sabse strong reversible factors mein se ek hai.",
    ),
    micro: copy("Smoking status captured.", "धूम्रपान-स्थिति दर्ज हो गई।", "Smoking status capture ho gaya."),
    options: [
      { value: "yes", label: copy("Yes", "हाँ", "Haan"), note: copy("Any regular smoking counts", "नियमित धूम्रपान को गिना जाएगा", "Any regular smoking count hoga") },
      { value: "no", label: copy("No", "नहीं", "Nahin"), note: copy("Not currently smoking", "अभी धूम्रपान नहीं", "Abhi smoke nahin karte") },
    ],
    ask: () => true,
  },
  {
    id: "cigarettes_per_day",
    kind: "choice",
    vibe: "vitals",
    title: copy(
      "If you smoke, how much do you usually smoke in a day?",
      "यदि आप धूम्रपान करते हैं, तो सामान्यतः एक दिन में कितना धूम्रपान करते हैं?",
      "Agar aap smoke karte ho, to usually ek din mein kitna smoke karte ho?",
    ),
    body: copy(
      "Daily exposure changes vascular risk much more than occasional exposure.",
      "रोज़ाना का एक्सपोज़र धमनियों के जोखिम को कभी-कभी होने वाले एक्सपोज़र की तुलना में अधिक बदलता है।",
      "Daily exposure vascular risk ko occasional smoking se kaafi zyada badalta hai.",
    ),
    micro: copy("Smoking load noted.", "धूम्रपान-भार दर्ज हो गया।", "Smoking load note ho gaya."),
    options: [
      { value: "1_5", label: copy("1 to 5", "1 से 5", "1 se 5") },
      { value: "6_10", label: copy("6 to 10", "6 से 10", "6 se 10") },
      { value: "10_plus", label: copy("More than 10", "10 से अधिक", "10 se zyada") },
    ],
    ask: (form) => form.smoking === "yes",
  },
  {
    id: "diabetes",
    kind: "choice",
    vibe: "vitals",
    title: copy("Have you been diagnosed with diabetes?", "क्या आपको मधुमेह का निदान हुआ है?", "Kya aapko diabetes diagnose hui hai?"),
    body: copy(
      "Diabetes changes cardiovascular risk even before severe symptoms appear.",
      "गंभीर लक्षण आने से पहले भी मधुमेह कार्डियोवैस्कुलर जोखिम को बदल देता है।",
      "Diabetes severe symptoms se pehle hi cardiovascular risk ko change kar deta hai.",
    ),
    micro: copy("Diabetes status noted.", "मधुमेह-स्थिति दर्ज हो गई।", "Diabetes status note ho gaya."),
    options: [
      { value: "yes", label: copy("Yes", "हाँ", "Haan"), note: copy("Type 1 or Type 2", "टाइप 1 या टाइप 2", "Type 1 ya Type 2") },
      { value: "no", label: copy("No", "नहीं", "Nahin"), note: copy("No diagnosis", "निदान नहीं", "Diagnose nahin hui") },
    ],
    ask: () => true,
  },
  {
    id: "family_history",
    kind: "choice",
    vibe: "vitals",
    title: copy("Family history of heart disease?", "क्या परिवार में हृदय-रोग का इतिहास है?", "Kya family history mein heart disease hai?"),
    body: copy(
      "Heart disease in close relatives can shift the baseline risk upward.",
      "निकट सम्बन्धियों में हृदय-रोग होना बेसलाइन जोखिम को ऊपर ले जा सकता है।",
      "Close relatives mein heart disease hona baseline risk ko upar le ja sakta hai.",
    ),
    micro: copy("Family history recorded.", "पारिवारिक इतिहास दर्ज हो गया।", "Family history record ho gaya."),
    options: [
      { value: "yes", label: copy("Yes", "हाँ", "Haan"), note: copy("Parents or siblings", "माता-पिता या भाई-बहन", "Parents ya siblings") },
      { value: "no", label: copy("No", "नहीं", "Nahin"), note: copy("No known history", "कोई ज्ञात इतिहास नहीं", "No known history") },
    ],
    ask: () => true,
  },
  {
    id: "activity_level",
    kind: "choice",
    vibe: "activity",
    title: copy("How active is your usual week?", "आपका सामान्य सप्ताह कितना सक्रिय होता है?", "Aapka usual week kitna active hota hai?"),
    body: copy(
      "Movement strongly affects blood pressure, glucose control, and recovery reserve.",
      "गतिविधि का स्तर रक्तचाप, ग्लूकोज़ नियंत्रण और रिकवरी-क्षमता पर गहरा प्रभाव डालता है।",
      "Movement blood pressure, glucose control aur recovery reserve par strong effect daalta hai.",
    ),
    micro: copy("Activity pattern captured.", "गतिविधि-पैटर्न दर्ज हो गया।", "Activity pattern capture ho gaya."),
    options: [
      { value: "low", label: copy("Mostly inactive", "अधिकतर निष्क्रिय", "Mostly inactive"), note: copy("Less than 60 min/week", "60 मिनट/सप्ताह से कम", "60 min/week se kam") },
      { value: "medium", label: copy("Somewhat active", "मध्यम सक्रिय", "Somewhat active"), note: copy("Some weekly movement", "सप्ताह में कुछ गतिविधि", "Week mein kuch movement") },
      { value: "high", label: copy("Regularly active", "नियमित रूप से सक्रिय", "Regularly active"), note: copy("150+ min/week", "150+ मिनट/सप्ताह", "150+ min/week") },
    ],
    ask: () => true,
  },
  {
    id: "sitting",
    kind: "choice",
    vibe: "activity",
    title: copy("How long do you usually sit in a day?", "आप एक दिन में सामान्यतः कितनी देर बैठते हैं?", "Aap ek din mein usually kitni der baithe rehte ho?"),
    body: copy(
      "Long sitting time can raise risk even in people who exercise.",
      "लम्बे समय तक बैठना उन लोगों में भी जोखिम बढ़ा सकता है जो व्यायाम करते हैं।",
      "Lambi sitting un logon mein bhi risk badha sakti hai jo exercise karte hain.",
    ),
    micro: copy("Sitting pattern noted.", "बैठने का पैटर्न दर्ज हो गया।", "Sitting pattern note ho gaya."),
    options: [
      { value: "high", label: copy("8+ hours", "8+ घंटे", "8+ ghante") },
      { value: "medium", label: copy("4 to 8 hours", "4 से 8 घंटे", "4 se 8 ghante") },
      { value: "low", label: copy("Under 4 hours", "4 घंटे से कम", "4 ghante se kam") },
    ],
    ask: () => true,
  },
  {
    id: "exertion_response",
    kind: "choice",
    vibe: "activity",
    title: copy(
      "How does your body usually respond to brisk walking, stairs, or moderate effort?",
      "तेज़ चलने, सीढ़ियाँ चढ़ने या मध्यम प्रयास पर आपका शरीर सामान्यतः कैसी प्रतिक्रिया देता है?",
      "Brisk walk, stairs ya moderate effort par aapka body usually kaisi response deti hai?",
    ),
    body: copy(
      "Effort tolerance is one of the most useful early functional heart signals.",
      "प्रयास-सहनशीलता हृदय की प्रारम्भिक कार्यात्मक स्थिति समझने के सबसे उपयोगी संकेतों में से एक है।",
      "Effort tolerance heart ki early functional picture samajhne ke sabse useful signals mein se ek hai.",
    ),
    micro: copy("Effort response captured.", "प्रयास-प्रतिक्रिया दर्ज हो गई।", "Effort response capture ho gaya."),
    options: [
      { value: "easy", label: copy("Feels easy", "आसान लगता है", "Easy lagta hai") },
      { value: "noticeable", label: copy("Noticeable strain", "थोड़ा दबाव महसूस होता है", "Thoda strain mehsoos hota hai") },
      { value: "strained", label: copy("Harder than it should feel", "जितना होना चाहिए उससे अधिक कठिन लगता है", "Jitna hona chahiye usse zyada hard lagta hai") },
    ],
    ask: () => true,
  },
  {
    id: "chest_symptom_pattern",
    kind: "choice",
    vibe: "symptoms",
    title: copy(
      "When discomfort happens, which chest feeling is closest to what you notice?",
      "यदि असुविधा होती है, तो छाती में कौन-सी अनुभूति सबसे अधिक मिलती-जुलती है?",
      "Agar discomfort hota hai, to chest mein kaunsi feeling sabse close lagti hai?",
    ),
    body: copy(
      "This helps separate muscular strain, stress-linked symptoms, and pressure patterns worth tracking.",
      "इससे मांसपेशीय खिंचाव, तनाव-सम्बन्धी लक्षण और ध्यान देने योग्य दबाव-पैटर्न को अलग समझने में मदद मिलती है।",
      "Isse muscular strain, stress-linked symptoms aur pressure patterns ko alag samajhne mein madad milti hai.",
    ),
    micro: copy("Chest symptom pattern noted.", "छाती-लक्षण पैटर्न दर्ज हो गया।", "Chest symptom pattern note ho gaya."),
    options: [
      { value: "none", label: copy("No chest discomfort", "कोई छाती असुविधा नहीं", "No chest discomfort") },
      { value: "tightness", label: copy("Tightness or pressure", "जकड़न या दबाव", "Tightness ya pressure") },
      { value: "sharp", label: copy("Sharp or pinpoint pain", "तेज़ या चुभने जैसा दर्द", "Sharp ya chubhne jaisa pain") },
      { value: "burning", label: copy("Burning or heaviness", "जलन या भारीपन", "Burning ya heaviness") },
    ],
    ask: (form) => form.exertion_response !== "" || form.stress === "high",
  },
  {
    id: "breathlessness_pattern",
    kind: "choice",
    vibe: "symptoms",
    title: copy(
      "If shortness of breath appears, when is it most noticeable?",
      "यदि साँस फूलती है, तो यह सबसे अधिक कब महसूस होती है?",
      "Agar saans phoolti hai, to yeh sabse zyada kab notice hoti hai?",
    ),
    body: copy(
      "Timing matters because breathlessness at stairs, flat walk, or rest means different things.",
      "समय महत्त्वपूर्ण है क्योंकि सीढ़ियों, सामान्य चलने या आराम की अवस्था में साँस फूलना अलग अर्थ रखता है।",
      "Timing important hai kyunki stairs, flat walk ya rest par breathlessness ka meaning alag hota hai.",
    ),
    micro: copy("Breathlessness pattern captured.", "साँस फूलने का पैटर्न दर्ज हो गया।", "Breathlessness pattern capture ho gaya."),
    options: [
      { value: "none", label: copy("It does not happen", "ऐसा नहीं होता", "Aisa nahin hota") },
      { value: "stairs", label: copy("Mostly on stairs or uphill", "मुख्यतः सीढ़ियों या चढ़ाई पर", "Mostly stairs ya uphill par") },
      { value: "flat_walk", label: copy("Even on a normal flat walk", "सामान्य समतल चलने पर भी", "Normal flat walk par bhi") },
      { value: "rest", label: copy("Sometimes even at rest", "कभी-कभी आराम में भी", "Kabhi-kabhi rest mein bhi") },
    ],
    ask: (form) => form.exertion_response !== "easy" || form.chest_symptom_pattern === "tightness",
  },
  {
    id: "recovery_after_effort",
    kind: "choice",
    vibe: "symptoms",
    title: copy(
      "After moderate effort, how quickly do you usually feel normal again?",
      "मध्यम प्रयास के बाद आप सामान्यतः कितनी जल्दी फिर सामान्य महसूस करते हैं?",
      "Moderate effort ke baad aap usually kitni jaldi normal feel karte ho?",
    ),
    body: copy(
      "Recovery time helps us understand conditioning, strain, and reserve.",
      "रिकवरी का समय कंडीशनिंग, दबाव और शरीर की रिज़र्व-क्षमता को समझने में मदद करता है।",
      "Recovery time se conditioning, strain aur reserve samajhne mein madad milti hai.",
    ),
    micro: copy("Recovery pattern noted.", "रिकवरी-पैटर्न दर्ज हो गया।", "Recovery pattern note ho gaya."),
    options: [
      { value: "under_two", label: copy("Within 1 to 2 minutes", "1 से 2 मिनट में", "1 se 2 minute mein") },
      { value: "two_to_ten", label: copy("A few minutes", "कुछ मिनट लगते हैं", "Kuch minute lagte hain") },
      { value: "over_ten", label: copy("More than 10 minutes", "10 मिनट से अधिक", "10 minute se zyada") },
    ],
    ask: (form) => form.exertion_response === "noticeable" || form.exertion_response === "strained",
  },
  {
    id: "stress",
    kind: "choice",
    vibe: "lifestyle",
    title: copy("How much ongoing stress does your week usually carry?", "आपके सप्ताह में सामान्यतः कितना लगातार तनाव रहता है?", "Aapke week mein usually kitna ongoing stress rehta hai?"),
    body: copy(
      "Stress patterns can shape blood pressure, sleep, and symptom intensity together.",
      "तनाव के पैटर्न एक साथ रक्तचाप, नींद और लक्षणों की तीव्रता को प्रभावित कर सकते हैं।",
      "Stress patterns ek saath blood pressure, sleep aur symptom intensity ko affect kar sakte hain.",
    ),
    micro: copy("Stress pattern recorded.", "तनाव-पैटर्न दर्ज हो गया।", "Stress pattern record ho gaya."),
    options: [
      { value: "low", label: copy("Low", "कम", "Low") },
      { value: "medium", label: copy("Moderate", "मध्यम", "Moderate") },
      { value: "high", label: copy("High and frequent", "अधिक और बार-बार", "High aur frequent") },
    ],
    ask: () => true,
  },
  {
    id: "stress_trigger_pattern",
    kind: "choice",
    vibe: "lifestyle",
    title: copy(
      "When stress builds, what pattern feels most accurate?",
      "जब तनाव बढ़ता है, तो कौन-सा पैटर्न सबसे अधिक सही लगता है?",
      "Jab stress build hota hai, to kaunsa pattern sabse sahi lagta hai?",
    ),
    body: copy(
      "We use this to understand whether stress feels constant, work-driven, or comes in body-heavy episodes.",
      "इससे समझ आता है कि तनाव लगातार रहता है, काम से जुड़ा है, या शरीर-सम्बन्धी एपिसोड के रूप में आता है।",
      "Isse samajh aata hai ki stress constant rehta hai, workload-driven hai, ya body-heavy episodes mein aata hai.",
    ),
    micro: copy("Stress trigger pattern noted.", "तनाव-ट्रिगर पैटर्न दर्ज हो गया।", "Stress trigger pattern note ho gaya."),
    options: [
      { value: "workload", label: copy("Mostly workload driven", "मुख्यतः काम के दबाव से", "Mostly workload driven") },
      { value: "constant", label: copy("Feels constant through the day", "दिनभर लगभग लगातार", "Din bhar lagbhag constant") },
      { value: "episodes", label: copy("Comes in episodes with body symptoms", "एपिसोड के रूप में आता है और शरीर में असर देता है", "Episodes mein aata hai aur body symptoms deta hai") },
    ],
    ask: (form) => form.stress === "high",
  },
  {
    id: "sleep_quality",
    kind: "choice",
    vibe: "lifestyle",
    title: copy("How is your sleep quality most nights?", "अधिकतर रातों में आपकी नींद की गुणवत्ता कैसी रहती है?", "Aksar raaton mein sleep quality kaisi rehti hai?"),
    body: copy(
      "Sleep is where cardiovascular recovery happens.",
      "नींद वह समय है जब कार्डियोवैस्कुलर रिकवरी होती है।",
      "Sleep wahi time hai jab cardiovascular recovery hoti hai.",
    ),
    micro: copy("Sleep quality captured.", "नींद की गुणवत्ता दर्ज हो गई।", "Sleep quality capture ho gayi."),
    options: [
      { value: "poor", label: copy("Poor", "खराब", "Poor") },
      { value: "ok", label: copy("Average", "औसत", "Average") },
      { value: "good", label: copy("Good", "अच्छी", "Good") },
    ],
    ask: () => true,
  },
  {
    id: "sleep_hours",
    kind: "number",
    min: 3,
    max: 12,
    placeholder: "7",
    vibe: "lifestyle",
    title: copy("How many hours do you actually sleep?", "आप वास्तव में कितने घंटे सोते हैं?", "Aap actually kitne ghante sote ho?"),
    body: copy(
      "Sleep duration helps us estimate whether recovery debt is building up.",
      "नींद की अवधि से यह समझ आता है कि क्या रिकवरी-डेब्ट बढ़ रही है।",
      "Sleep duration se samajh aata hai ki recovery debt build ho rahi hai ya nahin.",
    ),
    micro: copy("Sleep duration recorded.", "नींद की अवधि दर्ज हो गई।", "Sleep duration record ho gayi."),
    ask: (form) => form.sleep_quality !== "good" || form.stress === "high",
  },
  {
    id: "snoring_pattern",
    kind: "choice",
    vibe: "lifestyle",
    title: copy(
      "Do you snore loudly or wake up gasping at times?",
      "क्या आप ज़ोर से खर्राटे लेते हैं या कभी-कभी हाँफते हुए उठते हैं?",
      "Kya aap zor se snore karte ho ya kabhi-kabhi gasping ke saath uthte ho?",
    ),
    body: copy(
      "Sleep-disordered breathing can worsen fatigue, blood pressure, and overnight recovery.",
      "नींद के दौरान साँस लेने की समस्या थकान, रक्तचाप और रात की रिकवरी को बिगाड़ सकती है।",
      "Sleep breathing problem fatigue, blood pressure aur overnight recovery ko kharab kar sakti hai.",
    ),
    micro: copy("Sleep breathing pattern noted.", "नींद के दौरान साँस का पैटर्न दर्ज हो गया।", "Sleep breathing pattern note ho gaya."),
    options: [
      { value: "no", label: copy("Almost never", "लगभग कभी नहीं", "Almost never") },
      { value: "sometimes", label: copy("Sometimes", "कभी-कभी", "Sometimes") },
      { value: "often", label: copy("Often", "अक्सर", "Often") },
    ],
    ask: (form) => form.sleep_quality === "poor" || Number(form.sleep_hours || 0) <= 6,
  },
  {
    id: "diet",
    kind: "choice",
    vibe: "lifestyle",
    title: copy("Which option best matches your regular diet?", "आपके नियमित आहार से कौन-सा विकल्प सबसे अधिक मेल खाता है?", "Aapke regular diet ko kaunsa option best match karta hai?"),
    body: copy(
      "Diet influences blood pressure, glucose, lipids, and inflammation together.",
      "आहार एक साथ रक्तचाप, ग्लूकोज़, लिपिड और सूजन को प्रभावित करता है।",
      "Diet ek saath blood pressure, glucose, lipids aur inflammation ko affect karta hai.",
    ),
    micro: copy("Diet pattern recorded.", "आहार-पैटर्न दर्ज हो गया।", "Diet pattern record ho gaya."),
    options: [
      { value: "frequent", label: copy("Mostly processed or outside food", "अधिकतर प्रोसेस्ड या बाहर का भोजन", "Mostly processed ya outside food") },
      { value: "moderate", label: copy("Mixed", "मिश्रित", "Mixed") },
      { value: "rare", label: copy("Mostly home-cooked", "अधिकतर घर का बना भोजन", "Mostly home-cooked") },
    ],
    ask: () => true,
  },
  {
    id: "fruit_veg_servings",
    kind: "choice",
    vibe: "lifestyle",
    title: copy("How many fruit and vegetable servings do you get daily?", "आप प्रतिदिन फल और सब्ज़ियों की कितनी सर्विंग लेते हैं?", "Aap daily fruits aur vegetables ki kitni servings lete ho?"),
    body: copy(
      "This helps estimate how protective your current food pattern really is.",
      "इससे यह अनुमान मिलता है कि आपका वर्तमान आहार वास्तव में कितना सुरक्षात्मक है।",
      "Isse andaza milta hai ki aapka current diet pattern kitna protective hai.",
    ),
    micro: copy("Protective food markers captured.", "सुरक्षात्मक आहार-संकेत दर्ज हो गए।", "Protective food markers capture ho gaye."),
    options: [
      { value: "0_1", label: copy("0 to 1 servings", "0 से 1 सर्विंग", "0 se 1 servings") },
      { value: "2_3", label: copy("2 to 3 servings", "2 से 3 सर्विंग", "2 se 3 servings") },
      { value: "4_plus", label: copy("4 or more", "4 या अधिक", "4 ya zyada") },
    ],
    ask: () => true,
  },
  {
    id: "sugary_drinks",
    kind: "choice",
    vibe: "lifestyle",
    title: copy("How often do sweetened drinks show up in your week?", "आपके सप्ताह में मीठे पेय कितनी बार शामिल होते हैं?", "Aapke week mein sweet drinks kitni baar aati hain?"),
    body: copy(
      "Sweetened beverages can quickly increase glucose and triglyceride burden.",
      "मीठे पेय जल्दी ही ग्लूकोज़ और ट्राइग्लिसराइड-भार बढ़ा सकते हैं।",
      "Sweet drinks glucose aur triglyceride burden ko jaldi badha sakte hain.",
    ),
    micro: copy("Sugary drink intake noted.", "मीठे पेयों का सेवन दर्ज हो गया।", "Sugary drink intake note ho gaya."),
    options: [
      { value: "rare", label: copy("Rarely", "बहुत कम", "Rarely") },
      { value: "few_weekly", label: copy("A few times a week", "सप्ताह में कुछ बार", "Hafte mein kuch baar") },
      { value: "daily", label: copy("Daily or near daily", "लगभग रोज़", "Daily ya near daily") },
    ],
    ask: (form) => form.diet !== "rare" || form.diabetes === "yes",
  },
  {
    id: "salt_intake",
    kind: "choice",
    vibe: "lifestyle",
    title: copy("How salty are your usual meals?", "आपका सामान्य भोजन कितना नमकीन होता है?", "Aapka usual khana kitna salty hota hai?"),
    body: copy(
      "Excess sodium can quietly worsen blood pressure trends.",
      "अधिक सोडियम चुपचाप रक्तचाप के पैटर्न को बिगाड़ सकता है।",
      "Excess sodium quietly blood pressure trend ko bigaad sakta hai.",
    ),
    micro: copy("Salt pattern recorded.", "नमक-पैटर्न दर्ज हो गया।", "Salt pattern record ho gaya."),
    options: [
      { value: "low", label: copy("Usually mild", "आमतौर पर कम", "Usually mild") },
      { value: "moderate", label: copy("Mixed", "मिश्रित", "Mixed") },
      { value: "high", label: copy("Often salty or packaged", "अक्सर नमकीन या पैकेज्ड", "Often salty ya packaged") },
    ],
    ask: (form) => form.stress !== "low" || form.diet !== "rare" || form.family_history === "yes",
  },
  {
    id: "meal_timing_pattern",
    kind: "choice",
    vibe: "lifestyle",
    title: copy("How regular are your meal timings?", "आपके भोजन का समय कितना नियमित है?", "Aapke meals ka timing kitna regular hai?"),
    body: copy(
      "Irregular eating can affect glucose control, cravings, and energy stability.",
      "अनियमित भोजन ग्लूकोज़ नियंत्रण, भूख और ऊर्जा-स्थिरता को प्रभावित कर सकता है।",
      "Irregular eating glucose control, cravings aur energy stability ko affect kar sakta hai.",
    ),
    micro: copy("Meal timing captured.", "भोजन-समय दर्ज हो गया।", "Meal timing capture ho gaya."),
    options: [
      { value: "regular", label: copy("Mostly regular", "अधिकतर नियमित", "Mostly regular") },
      { value: "late_night", label: copy("Late-night eating is common", "देर रात खाना आम है", "Late-night eating common hai") },
      { value: "skipped", label: copy("Meals are often skipped", "भोजन अक्सर छूट जाता है", "Meals aksar skip ho jaate hain") },
    ],
    ask: (form) => form.diabetes === "yes" || form.sugary_drinks !== "" || form.diet === "frequent",
  },
];

export const CLINICAL_FIELDS = [
  {
    id: "systolic_bp",
    label: copy("Systolic BP", "सिस्टोलिक रक्तचाप", "Systolic BP"),
    unit: "mmHg",
    placeholder: "120",
    min: 80,
    max: 240,
    helper: copy("Top number from a blood pressure reading.", "रक्तचाप रीडिंग का ऊपर वाला मान।", "BP reading ka top number."),
    standard: copy("AHA: Normal <120, Elevated 120-129, Stage 1 130-139, Stage 2 >=140", "AHA: सामान्य <120, Elevated 120-129, Stage 1 130-139, Stage 2 >=140", "AHA: Normal <120, Elevated 120-129, Stage 1 130-139, Stage 2 >=140"),
  },
  {
    id: "diastolic_bp",
    label: copy("Diastolic BP", "डायस्टोलिक रक्तचाप", "Diastolic BP"),
    unit: "mmHg",
    placeholder: "80",
    min: 40,
    max: 160,
    helper: copy("Bottom number from a blood pressure reading.", "रक्तचाप रीडिंग का नीचे वाला मान।", "BP reading ka bottom number."),
    standard: copy("AHA: Normal <80, Stage 1 80-89, Stage 2 >=90", "AHA: सामान्य <80, Stage 1 80-89, Stage 2 >=90", "AHA: Normal <80, Stage 1 80-89, Stage 2 >=90"),
  },
  {
    id: "cholesterol",
    label: copy("Total Cholesterol", "कुल कोलेस्ट्रॉल", "Total Cholesterol"),
    unit: "mg/dL",
    placeholder: "195",
    min: 90,
    max: 400,
    helper: copy("Value from a recent lipid profile.", "हाल की लिपिड-प्रोफ़ाइल से लिया गया मान।", "Recent lipid profile ka value."),
    standard: copy("ATP-III: Desirable <200, Borderline 200-239, High >=240", "ATP-III: वांछनीय <200, Borderline 200-239, High >=240", "ATP-III: Desirable <200, Borderline 200-239, High >=240"),
  },
  {
    id: "hdl_cholesterol",
    label: copy("HDL Cholesterol", "एचडीएल कोलेस्ट्रॉल", "HDL Cholesterol"),
    unit: "mg/dL",
    placeholder: "55",
    min: 15,
    max: 100,
    helper: copy("Often called good cholesterol.", "इसे अक्सर अच्छा कोलेस्ट्रॉल कहा जाता है।", "Isse good cholesterol bhi kehte hain."),
    standard: copy("AHA: Low <40, Protective >=60", "AHA: Low <40, Protective >=60", "AHA: Low <40, Protective >=60"),
  },
  {
    id: "ldl_cholesterol",
    label: copy("LDL Cholesterol", "एलडीएल कोलेस्ट्रॉल", "LDL Cholesterol"),
    unit: "mg/dL",
    placeholder: "110",
    min: 40,
    max: 300,
    helper: copy("Often called bad cholesterol.", "इसे अक्सर खराब कोलेस्ट्रॉल कहा जाता है।", "Isse bad cholesterol bhi kehte hain."),
    standard: copy("ATP-III: Optimal <100, Near-optimal 100-129, Borderline 130-159, High >=160", "ATP-III: Optimal <100, Near-optimal 100-129, Borderline 130-159, High >=160", "ATP-III: Optimal <100, Near-optimal 100-129, Borderline 130-159, High >=160"),
  },
  {
    id: "fasting_glucose",
    label: copy("Fasting Glucose", "उपवास ग्लूकोज़", "Fasting Glucose"),
    unit: "mg/dL",
    placeholder: "92",
    min: 50,
    max: 400,
    helper: copy("Measured after an overnight fast.", "रातभर के उपवास के बाद लिया गया मान।", "Overnight fast ke baad liya gaya value."),
    standard: copy("ADA: Normal <100, Prediabetes 100-125, Diabetes >=126", "ADA: सामान्य <100, Prediabetes 100-125, Diabetes >=126", "ADA: Normal <100, Prediabetes 100-125, Diabetes >=126"),
  },
  {
    id: "triglycerides",
    label: copy("Triglycerides", "ट्राइग्लिसराइड", "Triglycerides"),
    unit: "mg/dL",
    placeholder: "140",
    min: 30,
    max: 600,
    helper: copy("Also part of a lipid profile.", "यह भी लिपिड-प्रोफ़ाइल का हिस्सा है।", "Yeh bhi lipid profile ka hissa hota hai."),
    standard: copy("AHA: Normal <150, Borderline 150-199, High >=200", "AHA: सामान्य <150, Borderline 150-199, High >=200", "AHA: Normal <150, Borderline 150-199, High >=200"),
  },
];
